Добавлена домашняя работа Homework1 - types and operators
SobolevaAnna/TMS_AQA_SOBOLEVA pull request #1
Opened 2024-01-15 16:53 UTC by SobolevaAnna

2024-01-22 16:49 UTC, wildpioneer requested changes

2024-01-22 16:49 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (num0 < -50 && num0 > 50)
По условию все же подразумевается включение границ

2024-01-22 16:49 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (numparity2 % 10 == 0 || numparity2 % 10 == 2 || numparity2 % 10 == 4 || numparity2 % 10 == 6 || numparity2 % 10 == 8)
Не понял данного подхода - можно пояснение в словах?

2024-01-23 15:00 UTC, SobolevaAnna commented on TypesAndOperators/Program.cs
> +            if (numparity2 % 10 == 0 || numparity2 % 10 == 2 || numparity2 % 10 == 4 || numparity2 % 10 == 6 || numparity2 % 10 == 8)
Берем последнюю цифру числа и смотрим, если она или 0, или 2, или 4, или 6, или 8, то тогда считаем его четным

2024-01-29 09:35 UTC, wildpioneer commented
Проверено

2024-01-29 09:35 UTC, closed without merging